import { DashboardNav } from "@/components/dashboard/nav";
import { updateCompanySettingsAction } from "@/features/settings/actions";
import { requireUser } from "@/lib/auth/require-user";
import { requireCurrentOrganization } from "@/lib/organizations/current";
import { createClient } from "@/lib/supabase/server";

export const dynamic = "force-dynamic";
type Props = { searchParams: Promise<Record<string,string|string[]|undefined>> };
export default async function CompanySettingsPage({ searchParams }: Props) {
  await requireUser(); const organization = await requireCurrentOrganization(); const supabase = await createClient();
  const { data: company } = await supabase.from("organizations").select("name,segment,phone,whatsapp,email,city,state,logo_url,address,business_hours").eq("id",organization.id).single();
  const params=await searchParams; const status=typeof params.status==="string"?params.status:""; const error=typeof params.erro==="string"?params.erro:""; const canManage=["owner","admin"].includes(organization.role);
  return <><DashboardNav organizationName={organization.name}/><main className="container-shell py-10"><p className="text-sm font-bold uppercase tracking-widest text-blue-700">Configurações</p><h1 className="mt-1 text-3xl font-black">Dados da empresa</h1><p className="muted mt-2">Estas informações alimentam o site, os orçamentos e o contato comercial.</p>{status?<p className="mt-5 rounded-xl bg-emerald-50 p-4 text-sm font-semibold">Configurações salvas.</p>:null}{error?<p className="mt-5 rounded-xl bg-amber-50 p-4 text-sm">Não foi possível salvar.</p>:null}
  <form action={updateCompanySettingsAction} className="card mt-7 grid gap-4 p-6 lg:grid-cols-2"><div className="lg:col-span-2 flex items-center gap-4">{company?.logo_url?<img src={company.logo_url} alt="Logo da empresa" className="h-20 w-20 rounded-xl object-contain border border-black/5"/>:null}<label className="field flex-1"><span>Logo</span><input type="file" name="logo" accept="image/jpeg,image/png,image/webp" disabled={!canManage}/></label></div><label className="field"><span>Nome</span><input name="name" required defaultValue={company?.name??""} disabled={!canManage}/></label><label className="field"><span>Segmento</span><input name="segment" defaultValue={company?.segment??""} disabled={!canManage}/></label><label className="field"><span>Telefone</span><input name="phone" defaultValue={company?.phone??""} disabled={!canManage}/></label><label className="field"><span>WhatsApp</span><input name="whatsapp" defaultValue={company?.whatsapp??""} disabled={!canManage}/></label><label className="field"><span>E-mail</span><input name="email" type="email" defaultValue={company?.email??""} disabled={!canManage}/></label><label className="field"><span>Cidade</span><input name="city" defaultValue={company?.city??""} disabled={!canManage}/></label><label className="field"><span>UF</span><input name="state" maxLength={2} defaultValue={company?.state??""} disabled={!canManage}/></label><label className="field lg:col-span-2"><span>Endereço</span><input name="address" maxLength={300} defaultValue={company?.address??""} disabled={!canManage}/></label><label className="field lg:col-span-2"><span>Horário de atendimento</span><textarea name="business_hours" maxLength={1000} defaultValue={company?.business_hours??""} disabled={!canManage}/></label>{canManage?<button className="btn-primary lg:col-span-2 lg:justify-self-start" type="submit">Salvar empresa</button>:<p className="muted lg:col-span-2 text-sm">Somente proprietário ou administrador pode alterar os dados da empresa.</p>}</form></main></>;
}
