import Link from "next/link";
import { notFound } from "next/navigation";
import { DashboardNav } from "@/components/dashboard/nav";
import { EmailTemplateFields, WhatsAppTemplateFields } from "@/components/communications/template-fields";
import { EventTimeline } from "@/components/timeline/event-timeline";
import { LeadAIReply } from "@/components/ai/lead-reply";
import { sendLeadEmailAction, sendLeadWhatsAppTemplateAction, sendLeadWhatsAppTextAction } from "@/features/communications/actions";
import { scheduleLeadFollowUpAction } from "@/features/crm/actions";
import { requireUser } from "@/lib/auth/require-user";
import { isTransactionalEmailConfigured } from "@/lib/communications/email";
import { leadCommunicationTemplates } from "@/lib/communications/templates";
import { requireCurrentOrganization } from "@/lib/organizations/current";
import { hasFeature, requireFeature } from "@/lib/plans/entitlements";
import { formatDate, formatMoney } from "@/lib/format";
import { createClient } from "@/lib/supabase/server";

export const dynamic="force-dynamic";
type Props={params:Promise<{id:string}>;searchParams:Promise<Record<string,string|string[]|undefined>>};
type Event={id:string;event_type:string;metadata:Record<string,unknown>|null;created_at:string};
type Quote={id:string;status:string;total_cents:number;created_at:string};
type Message={id:string;channel:"email"|"whatsapp";direction:"inbound"|"outbound";status:string;subject:string|null;body:string|null;message_type:string|null;template_name:string|null;sender:string|null;recipient:string|null;created_at:string;received_at:string|null};

export default async function LeadDetailPage({params,searchParams}:Props){
  await requireFeature("crm");await requireUser();const organization=await requireCurrentOrganization();const {id}=await params;const query=await searchParams;const supabase=await createClient();const [canSuggestWithAI,canEmail,canWhatsApp]=await Promise.all([hasFeature("ai_responses"),hasFeature("email_transactional"),hasFeature("whatsapp_official")]);
  const [{data:lead},{data:events},{data:quotes},{data:messages},{data:whatsConnection}]=await Promise.all([
    supabase.from("leads").select("id,name,phone,whatsapp,email,company,source,status,tags,notes,potential_value_cents,interest,last_contact_at,next_contact_at,created_at").eq("organization_id", organization.id).eq("id",id).maybeSingle(),
    supabase.from("events").select("id,event_type,metadata,created_at").eq("organization_id", organization.id).eq("entity_type","lead").eq("entity_id",id).order("created_at",{ascending:false}).limit(200),
    supabase.from("quotes").select("id,status,total_cents,created_at").eq("organization_id", organization.id).eq("lead_id",id).order("created_at",{ascending:false}).limit(50),
    supabase.from("communication_messages").select("id,channel,direction,status,subject,body,message_type,template_name,sender,recipient,created_at,received_at").eq("organization_id", organization.id).eq("lead_id",id).order("created_at",{ascending:false}).limit(100),
    canWhatsApp?supabase.from("integration_connections").select("status").eq("organization_id", organization.id).eq("provider","whatsapp_cloud").maybeSingle():Promise.resolve({data:null,error:null})
  ]);
  if(!lead)notFound();const allMessages=(messages??[]) as Message[];const normalizedTarget=(lead.whatsapp||lead.phone||"").replace(/\D/g,"");const lastInbound=allMessages.find(m=>m.channel==="whatsapp"&&m.direction==="inbound"&&m.sender===normalizedTarget&&m.received_at);const windowOpen=Boolean(lastInbound?.received_at&&Date.now()-new Date(lastInbound.received_at).getTime()<24*60*60*1000);const templates=leadCommunicationTemplates({name:lead.name,interest:lead.interest});const emailReady=canEmail&&isTransactionalEmailConfigured();const whatsappReady=canWhatsApp&&whatsConnection?.status==="active";const status=typeof query.status==="string"?query.status:"";const error=typeof query.erro==="string"?query.erro:"";
  return <><DashboardNav organizationName={organization.name}/><main className="container-shell py-10"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-bold uppercase tracking-widest text-blue-700">Lead</p><h1 className="mt-1 text-3xl font-black">{lead.name}</h1><p className="muted mt-2">Histórico, follow-up e comunicação comercial deste contato.</p></div><div className="flex gap-2"><Link href="/crm" className="btn-secondary">Voltar ao CRM</Link><Link href={`/orcamentos?lead=${lead.id}`} className="btn-primary">Novo orçamento</Link></div></div>{status?<p className="mt-5 rounded-xl bg-emerald-50 p-4 text-sm font-semibold">{status==="email_enviado"?"E-mail aceito pelo provider para envio.":"Mensagem aceita pela API oficial do WhatsApp."}</p>:null}{error?<p className="mt-5 rounded-xl bg-amber-50 p-4 text-sm">Falha de comunicação: {error==="whatsapp_janela"?"a janela de atendimento livre está fechada; use um template aprovado.":error.replaceAll("_"," ")}.</p>:null}
  <section className="mt-7 grid gap-5 lg:grid-cols-[0.85fr_1.15fr]"><div className="grid content-start gap-5"><article className="card p-5"><h2 className="font-black">Dados</h2><dl className="mt-4 grid gap-2 text-sm"><div><dt className="muted">Contato</dt><dd>{lead.whatsapp||lead.phone||lead.email||"—"}</dd></div><div><dt className="muted">Empresa</dt><dd>{lead.company||"—"}</dd></div><div><dt className="muted">Origem</dt><dd>{lead.source}</dd></div><div><dt className="muted">Status</dt><dd>{lead.status}</dd></div><div><dt className="muted">Valor potencial</dt><dd>{formatMoney(lead.potential_value_cents)}</dd></div><div><dt className="muted">Entrada</dt><dd>{formatDate(lead.created_at)}</dd></div></dl>{lead.interest?<div className="mt-4"><p className="muted text-xs">Interesse</p><p className="mt-1 text-sm">{lead.interest}</p></div>:null}{lead.notes?<div className="mt-4"><p className="muted text-xs">Observações</p><p className="mt-1 whitespace-pre-wrap text-sm">{lead.notes}</p></div>:null}<div className="mt-5 border-t border-black/5 pt-4"><p className="text-sm font-bold">Próximo follow-up</p>{lead.next_contact_at?<p className="muted mt-1 text-xs">Agendado: {formatDate(lead.next_contact_at)}</p>:<p className="muted mt-1 text-xs">Nenhum retorno agendado.</p>}<form action={scheduleLeadFollowUpAction} className="mt-3 flex flex-wrap items-end gap-2"><input type="hidden" name="lead_id" value={lead.id}/><label className="field"><span>Data e hora</span><input name="next_contact_at" type="datetime-local" required/></label><button className="btn-secondary" type="submit">Agendar retorno</button></form></div></article>
  {canSuggestWithAI?<LeadAIReply leadId={lead.id}/>:null}
  <article className="card p-5"><div className="flex items-center justify-between gap-3"><h2 className="font-black">E-mail</h2><Link className="text-xs font-bold underline" href="/integracoes">Integrações</Link></div>{lead.email&&emailReady?<form action={sendLeadEmailAction} className="mt-4 grid gap-3"><input type="hidden" name="lead_id" value={lead.id}/><EmailTemplateFields templates={templates}/><button className="btn-secondary justify-self-start" type="submit">Enviar e-mail</button></form>:<p className="muted mt-3 text-sm">{!lead.email?"Este lead não possui e-mail.":!canEmail?"Seu plano não inclui e-mail transacional.":"O provider de e-mail ainda não está configurado no servidor."}</p>}</article>
  <article className="card p-5"><div className="flex items-center justify-between gap-3"><h2 className="font-black">WhatsApp oficial</h2><Link className="text-xs font-bold underline" href="/integracoes">Integrações</Link></div>{(lead.whatsapp||lead.phone)&&whatsappReady?<div className="mt-4 grid gap-5">{windowOpen?<form action={sendLeadWhatsAppTextAction} className="grid gap-3"><input type="hidden" name="lead_id" value={lead.id}/><p className="rounded-lg bg-emerald-50 p-3 text-xs font-semibold">Janela de atendimento aberta por mensagem recebida nas últimas 24h.</p><WhatsAppTemplateFields templates={templates}/><button className="btn-secondary justify-self-start" type="submit">Enviar pelo WhatsApp</button></form>:<p className="rounded-lg bg-amber-50 p-3 text-xs">Não há mensagem recebida nas últimas 24h. Para iniciar/retomar a conversa, use um template já aprovado na Meta.</p>}<form action={sendLeadWhatsAppTemplateAction} className="grid gap-3 border-t border-black/5 pt-4"><input type="hidden" name="lead_id" value={lead.id}/><label className="field"><span>Nome do template aprovado</span><input name="template_name" required pattern="[a-z0-9_]+" placeholder="orcamento_pronto"/></label><label className="field"><span>Idioma</span><input name="template_language" defaultValue="pt_BR" required/></label><label className="field"><span>Parâmetros do corpo</span><textarea name="template_parameters" placeholder={'Um parâmetro por linha\nJhony\nhttps://...'} maxLength={5000}/><small className="muted">A ordem deve ser a mesma das variáveis do template aprovado.</small></label><button className="btn-secondary justify-self-start" type="submit">Enviar template</button></form></div>:<p className="muted mt-3 text-sm">{!(lead.whatsapp||lead.phone)?"Este lead não possui telefone/WhatsApp.":!canWhatsApp?"Seu plano não inclui WhatsApp oficial.":"Conecte e valide o WhatsApp Cloud API em Integrações."}</p>}</article>
  <article className="card p-5"><h2 className="font-black">Orçamentos</h2><div className="mt-3 grid gap-2">{((quotes??[]) as Quote[]).map(q=><Link key={q.id} href={`/orcamentos/${q.id}`} className="rounded-xl border border-black/5 p-3 text-sm"><span className="font-semibold">{formatMoney(q.total_cents)}</span><span className="muted ml-2">{q.status} · {formatDate(q.created_at)}</span></Link>)}{(quotes??[]).length===0?<p className="muted text-sm">Nenhum orçamento.</p>:null}</div></article></div>
  <div className="grid content-start gap-5"><article className="card p-5"><h2 className="font-black">Linha do tempo</h2><div className="mt-4"><EventTimeline events={(events??[]) as Event[]}/></div></article><article className="card p-5"><h2 className="font-black">Mensagens</h2><div className="mt-4 grid gap-3">{allMessages.map(m=><div key={m.id} className="rounded-xl border border-black/5 p-3 text-sm"><div className="flex flex-wrap justify-between gap-2"><p className="font-bold">{m.channel==="email"?"E-mail":"WhatsApp"} · {m.direction==="inbound"?"Recebida":"Enviada"}</p><span className="muted text-xs">{m.status} · {formatDate(m.created_at)}</span></div>{m.subject?<p className="mt-2 font-semibold">{m.subject}</p>:null}<p className="muted mt-1 whitespace-pre-wrap text-sm">{m.template_name?`Template: ${m.template_name}${m.body?`\n${m.body}`:""}`:(m.body||`[${m.message_type||"mensagem"}]`)}</p></div>)}{!allMessages.length?<p className="muted text-sm">Nenhuma mensagem registrada.</p>:null}</div></article></div></section></main></>;
}
