export type SiteTemplate={key:string;name:string;description:string;payload:{headline:string;subheadline:string;about:string;primary_color:string;sections:Array<{type:string;enabled:boolean;sort_order:number;content:Record<string,unknown>}>}};
const base=(hero:string,sub:string,about:string,services:string,products:string,contact:string,cta:string,color:string):SiteTemplate["payload"]=>({headline:hero,subheadline:sub,about,primary_color:color,sections:[{type:"hero",enabled:true,sort_order:10,content:{title:hero,subtitle:sub,cta_label:"Solicitar orçamento",cta_target:"quote"}},{type:"about",enabled:true,sort_order:20,content:{title:"Sobre nós",text:about}},{type:"services",enabled:true,sort_order:30,content:{title:services}},{type:"products",enabled:true,sort_order:40,content:{title:products}},{type:"contact",enabled:true,sort_order:50,content:{title:"Fale com a gente",text:contact}},{type:"cta",enabled:true,sort_order:60,content:{title:cta,text:"Conte o que você precisa e receba um atendimento organizado.",label:"Solicitar orçamento",target:"quote"}}]});
export const siteTemplates:SiteTemplate[]=[
{key:"oficina",name:"Oficina",description:"Serviços automotivos, manutenção e orçamento rápido.",payload:base("Seu veículo em boas mãos","Serviços de manutenção com atendimento claro e orçamento organizado.","Apresente a experiência da oficina, os serviços realizados e os diferenciais reais da sua equipe.","Serviços da oficina","Peças e produtos","Envie os dados do veículo ou fale pelo WhatsApp.","Precisa cuidar do seu veículo?","#1f4f8f")},
{key:"agricola",name:"Empresa agrícola",description:"Manutenção, campo, implementos e serviços agrícolas.",payload:base("Soluções para manter sua operação no campo","Organize serviços, produtos e atendimento para sua operação agrícola.","Use este espaço para apresentar sua atuação no agronegócio, região atendida e capacidades reais da equipe.","Serviços agrícolas","Produtos e implementos","Conte sua necessidade e a equipe dará sequência ao atendimento.","Sua operação não pode parar","#3f6f45")},
{key:"loja",name:"Loja",description:"Catálogo, produtos em destaque e contato comercial.",payload:base("Encontre o que precisa em um só lugar","Conheça nossos produtos e fale diretamente com a equipe.","Apresente a história da loja, o tipo de produto vendido e os diferenciais reais do atendimento.","Atendimento e serviços","Produtos em destaque","Consulte disponibilidade e condições diretamente com nossa equipe.","Gostou de algum produto?","#6047a8")},
{key:"restaurante",name:"Restaurante",description:"Cardápio visual, localização e contato.",payload:base("Uma experiência feita para receber você","Conheça nossas opções e entre em contato com o restaurante.","Conte a proposta do restaurante, estilo da cozinha e informações reais que ajudam o cliente a escolher.","Experiências e serviços","Destaques do cardápio","Consulte horários, reservas e informações diretamente com a equipe.","Quer falar com o restaurante?","#9a472d")},
{key:"servicos",name:"Prestador de serviços",description:"Portfólio simples para autônomos e empresas de serviços.",payload:base("Serviço profissional, do primeiro contato à entrega","Mostre o que você faz e transforme visitas em oportunidades organizadas.","Explique sua experiência, área de atuação e diferenciais sem promessas que não possam ser comprovadas.","Como podemos ajudar","Soluções e materiais","Descreva sua necessidade para receber um atendimento adequado.","Vamos conversar sobre seu projeto?","#2457d6")}
];
export function getSiteTemplate(key:string){return siteTemplates.find(t=>t.key===key)??null;}
