import { notFound } from "next/navigation";
import { publicAppointmentAction } from "@/features/appointments/actions";
import { formatMoney } from "@/lib/format";
import { createClient } from "@/lib/supabase/server";

export const dynamic="force-dynamic";
type Props={params:Promise<{slug:string}>;searchParams:Promise<Record<string,string|string[]|undefined>>};
type Booking={organization:{name:string;slug:string;timezone:string;city:string|null;state:string|null};settings:{slot_duration_minutes:number;buffer_minutes:number;availability:Record<string,string[][]>};services:Array<{id:string;name:string;duration_minutes:number;starting_price_cents:number|null}>};
const dayNames:Record<string,string>={"1":"Segunda","2":"Terça","3":"Quarta","4":"Quinta","5":"Sexta","6":"Sábado","7":"Domingo"};
export default async function PublicBookingPage({params,searchParams}:Props){const {slug}=await params;const query=await searchParams;const supabase=await createClient();const {data,error}=await supabase.rpc("get_public_booking",{p_slug:slug});if(error||!data)notFound();const content=data as Booking;const status=typeof query.status==="string"?query.status:"";const err=typeof query.erro==="string"?query.erro:"";return <main className="container-shell py-12"><section className="mx-auto max-w-2xl"><p className="text-sm font-bold uppercase tracking-widest text-blue-700">Agendamento online</p><h1 className="mt-2 text-3xl font-black">{content.organization.name}</h1><p className="muted mt-2">Escolha o serviço e informe um horário dentro da disponibilidade da empresa. O sistema confirma somente se o horário ainda estiver livre.</p>{status?<p className="mt-5 rounded-xl bg-emerald-50 p-4 font-semibold">Agendamento confirmado. A empresa recebeu a solicitação.</p>:null}{err?<p className="mt-5 rounded-xl bg-amber-50 p-4 text-sm">{err==="ocupado"?"Esse horário acabou de ser ocupado. Escolha outro.":err==="limite"?"Muitas tentativas. Tente novamente mais tarde.":"Não foi possível agendar nesse horário. Confira os dados e a disponibilidade."}</p>:null}<form action={publicAppointmentAction.bind(null,slug)} className="card mt-7 grid gap-4 p-6"><label className="field"><span>Serviço</span><select name="service_id" required defaultValue=""><option value="" disabled>Selecione</option>{content.services.map(s=><option value={s.id} key={s.id}>{s.name}{s.starting_price_cents!=null?` — a partir de ${formatMoney(s.starting_price_cents)}`:""} · {s.duration_minutes} min</option>)}</select></label><label className="field"><span>Data e hora desejada</span><input type="datetime-local" name="start" required/><small className="muted">Horário local: {content.organization.timezone}</small></label><label className="field"><span>Seu nome</span><input name="name" required maxLength={160}/></label><label className="field"><span>WhatsApp/telefone</span><input name="phone" required maxLength={40}/></label><label className="hidden" aria-hidden="true"><span>Website</span><input name="website" tabIndex={-1} autoComplete="off"/></label><button className="btn-primary" type="submit">Confirmar agendamento</button></form><div className="card mt-5 p-5"><h2 className="font-black">Horários de atendimento</h2><div className="muted mt-2 grid gap-1 text-sm">{Object.entries(content.settings.availability).map(([day,ranges])=><p key={day}>{dayNames[day]??`Dia ${day}`}: {(ranges??[]).map(r=>r.join("–")).join(", ")}</p>)}</div></div></section></main>}
