import { DashboardNav } from "@/components/dashboard/nav";
import { CopilotForm, CopyForm, InsightsForm, QuoteAIForm } from "@/components/ai/ai-workspace";
import { isAIConfigured } from "@/lib/ai";
import { requireCurrentOrganization } from "@/lib/organizations/current";
import { hasFeature, requireFeature } from "@/lib/plans/entitlements";
import { createClient } from "@/lib/supabase/server";

type Usage={request_limit:number;token_limit:number;requests_used:number;tokens_used:number;estimated_cost_usd_micros:number;successful_requests:number;failed_requests:number};
function number(value:number){return new Intl.NumberFormat("pt-BR").format(value||0);}
function pct(value:number,total:number){return total>0?Math.min(100,(value/total)*100):0;}
export default async function AIAssistantPage(){
  await requireFeature("ai_assistant");const organization=await requireCurrentOrganization();const supabase=await createClient();const [usageResult,copy,quotes,insights]=await Promise.all([supabase.rpc("ai_usage_summary",{p_organization_id:organization.id}),hasFeature("ai_copy"),hasFeature("ai_quotes"),hasFeature("ai_insights")]);const u=(usageResult.data??{}) as Usage;const configured=isAIConfigured();const pricingConfigured=Number.isFinite(Number(process.env.OPENAI_INPUT_PRICE_PER_1M_USD))&&Number.isFinite(Number(process.env.OPENAI_OUTPUT_PRICE_PER_1M_USD));
  return <><DashboardNav organizationName={organization.name}/><main className="container-shell py-10"><div><p className="text-sm font-bold uppercase tracking-widest text-blue-700">Assistente IA</p><h1 className="mt-1 text-3xl font-black">IA com contexto controlado</h1><p className="muted mt-2 max-w-3xl">A IA recebe apenas o contexto necessário da sua organização, gera sugestões e nunca envia mensagens ou altera dados críticos automaticamente.</p></div>{!configured?<div className="mt-6 rounded-2xl border border-amber-200 bg-amber-50 p-5"><p className="font-bold">Integração ainda não configurada</p><p className="mt-1 text-sm">Defina <code>OPENAI_API_KEY</code> no ambiente do servidor. Enquanto isso, nenhuma resposta simulada será exibida.</p></div>:null}
  <section className="mt-7 grid gap-4 md:grid-cols-3"><div className="card p-5"><p className="muted text-sm">Solicitações no mês</p><p className="mt-2 text-2xl font-black">{number(u.requests_used)} / {number(u.request_limit)}</p><div className="mt-3 h-2 overflow-hidden rounded-full bg-black/5"><div className="h-full bg-black/70" style={{width:`${pct(u.requests_used,u.request_limit)}%`}}/></div></div><div className="card p-5"><p className="muted text-sm">Tokens no mês</p><p className="mt-2 text-2xl font-black">{number(u.tokens_used)} / {number(u.token_limit)}</p><div className="mt-3 h-2 overflow-hidden rounded-full bg-black/5"><div className="h-full bg-black/70" style={{width:`${pct(u.tokens_used,u.token_limit)}%`}}/></div></div><div className="card p-5"><p className="muted text-sm">Consumo estimado</p><p className="mt-2 text-2xl font-black">{pricingConfigured?`US$ ${((u.estimated_cost_usd_micros||0)/1_000_000).toFixed(4)}`:"Não configurado"}</p><p className="muted mt-1 text-xs">{u.successful_requests||0} concluídas · {u.failed_requests||0} falharam</p></div></section>
  <section className="mt-8 grid gap-5 lg:grid-cols-2"><CopilotForm/>{copy?<CopyForm/>:null}{quotes?<QuoteAIForm/>:null}{insights?<InsightsForm/>:null}</section>
  <p className="muted mt-8 text-xs">As sugestões podem conter erros. Dados de clientes são tratados como conteúdo não confiável e a IA não recebe autorização para executar ações no sistema.</p></main></>;
}
