import { NextRequest,NextResponse } from "next/server";
import { requireUser } from "@/lib/auth/require-user";
import { encryptIntegrationSecret } from "@/lib/communications/secret-box";
import { exchangeGoogleCalendarCode,googleUserEmail } from "@/lib/integrations/google-calendar";
import { createAdminClient } from "@/lib/supabase/admin";
import { getPublicAppUrl } from "@/lib/env";

export const runtime="nodejs";
export async function GET(request:NextRequest){const base=getPublicAppUrl();const user=await requireUser();const code=request.nextUrl.searchParams.get("code")||"";const state=request.nextUrl.searchParams.get("state")||"";if(!code||!state)return NextResponse.redirect(new URL("/integracoes?erro=google_oauth",base));const admin=createAdminClient();const {data:oauth}=await admin.from("oauth_states").select("id,organization_id,user_id,expires_at,used_at").eq("id",state).eq("provider","google_calendar").maybeSingle();if(!oauth||oauth.user_id!==user.id||oauth.used_at||Date.parse(oauth.expires_at)<Date.now())return NextResponse.redirect(new URL("/integracoes?erro=oauth_state",base));await admin.from("oauth_states").update({used_at:new Date().toISOString()}).eq("id",oauth.id);
  try{const token=await exchangeGoogleCalendarCode(code);const {data:existing}=await admin.from("integration_connections").select("id").eq("organization_id",oauth.organization_id).eq("provider","google_calendar").maybeSingle();let refresh=token.refresh_token;if(!refresh&&existing){const {data:old}=await admin.from("integration_secrets").select("ciphertext,iv,auth_tag").eq("connection_id",existing.id).maybeSingle();if(old){const {decryptIntegrationSecret}=await import("@/lib/communications/secret-box");try{const parsed=JSON.parse(decryptIntegrationSecret({ciphertext:old.ciphertext,iv:old.iv,authTag:old.auth_tag})) as {refresh_token?:string};refresh=parsed.refresh_token||"";}catch{}}}if(!refresh)throw new Error("GOOGLE_REFRESH_TOKEN_MISSING");const connectedEmail=await googleUserEmail(token.access_token);const bundle={...token,refresh_token:refresh};const {data:connection,error}=await admin.from("integration_connections").upsert({organization_id:oauth.organization_id,provider:"google_calendar",status:"configured",config:{calendar_id:"primary",connected_email:connectedEmail,scope:token.scope||null},last_verified_at:new Date().toISOString(),last_error:null,created_by:user.id},{onConflict:"organization_id,provider"}).select("id").single();if(error||!connection)throw new Error("GOOGLE_CONNECTION_SAVE");const encrypted=encryptIntegrationSecret(JSON.stringify(bundle));const {error:secretError}=await admin.from("integration_secrets").upsert({connection_id:connection.id,ciphertext:encrypted.ciphertext,iv:encrypted.iv,auth_tag:encrypted.authTag,updated_at:new Date().toISOString()},{onConflict:"connection_id"});if(secretError){await admin.from("integration_connections").update({status:"error",last_error:"GOOGLE_SECRET_SAVE"}).eq("id",connection.id);throw new Error("GOOGLE_SECRET_SAVE");}
    const {error:activateError}=await admin.from("integration_connections").update({status:"active",last_error:null,last_verified_at:new Date().toISOString()}).eq("id",connection.id);if(activateError)throw new Error("GOOGLE_CONNECTION_ACTIVATE");
    const {data:queued,error:queueError}=await admin.rpc("service_enqueue_google_calendar_backfill",{p_organization_id:oauth.organization_id,p_sync_key:oauth.id});
    await admin.from("audit_logs").insert({organization_id:oauth.organization_id,actor_user_id:user.id,action:"integration.google_calendar_connected",entity_type:"integration",entity_id:connection.id,metadata:{initial_sync_queued:queueError?null:Number(queued||0),initial_sync_error:queueError?.message?.slice(0,300)||null}});
    return NextResponse.redirect(new URL("/integracoes?status=google-calendar-conectado",base));}catch{return NextResponse.redirect(new URL("/integracoes?erro=google_calendar_oauth",base));}}
