import Link from "next/link";
import { ApiKeyForm,WebhookForm } from "@/components/developer/secret-forms";
import { DashboardNav } from "@/components/dashboard/nav";
import { retryWebhookDeliveryAction,revokeApiKeyAction,setWebhookEndpointStatusAction } from "@/features/developer/actions";
import { formatDate } from "@/lib/format";
import { requireCurrentOrganization } from "@/lib/organizations/current";
import { hasFeature } from "@/lib/plans/entitlements";
import { createClient } from "@/lib/supabase/server";

export const dynamic="force-dynamic";
type Props={searchParams:Promise<Record<string,string|string[]|undefined>>};
type ApiKeyRow={id:string;name:string;key_prefix:string;scopes:string[];status:string;expires_at:string|null;last_used_at:string|null;created_at:string};
type ApiLogRow={id:number;key_prefix:string;scope:string;method:string;route:string;response_status:number;duration_ms:number|null;request_id:string|null;created_at:string};
type EndpointRow={id:string;name:string;url:string;event_types:string[];status:string;signing_secret_prefix:string;last_success_at:string|null;last_failure_at:string|null;last_error:string|null;created_at:string};
type DeliveryRow={id:string;endpoint_id:string;endpoint_name:string;event_type:string;status:string;attempts:number;response_status:number|null;last_error:string|null;delivered_at:string|null;created_at:string};

export default async function DeveloperPage({searchParams}:Props){
  const organization=await requireCurrentOrganization();
  const supabase=await createClient();
  const query=await searchParams;
  const canManage=["owner","admin"].includes(organization.role);
  const [apiAllowed,webhooksAllowed]=await Promise.all([hasFeature("public_api"),hasFeature("outbound_webhooks")]);
  const [keysResult,usageResult,logsResult,endpointsResult,deliveriesResult]=await Promise.all([
    apiAllowed?supabase.rpc("list_api_keys",{p_organization_id:organization.id}):Promise.resolve({data:[],error:null}),
    apiAllowed?supabase.rpc("api_usage_summary",{p_organization_id:organization.id}):Promise.resolve({data:null,error:null}),
    apiAllowed&&canManage?supabase.rpc("list_api_request_logs",{p_organization_id:organization.id,p_limit:50}):Promise.resolve({data:[],error:null}),
    webhooksAllowed?supabase.rpc("list_webhook_endpoints",{p_organization_id:organization.id}):Promise.resolve({data:[],error:null}),
    webhooksAllowed?supabase.rpc("list_webhook_deliveries",{p_organization_id:organization.id,p_limit:50}):Promise.resolve({data:[],error:null})
  ]);
  const keys=(keysResult.data??[]) as ApiKeyRow[];
  const usage=(usageResult.data??null) as {last_24h?:number;errors_24h?:number;active_keys?:number}|null;
  const logs=(logsResult.data??[]) as ApiLogRow[];
  const endpoints=(endpointsResult.data??[]) as EndpointRow[];
  const deliveries=(deliveriesResult.data??[]) as DeliveryRow[];
  const status=typeof query.status==="string"?query.status:"";
  const error=typeof query.erro==="string"?query.erro:"";

  return <><DashboardNav organizationName={organization.name}/><main className="container-shell py-10">
    <div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-bold uppercase tracking-widest text-blue-700">Desenvolvedores</p><h1 className="mt-1 text-3xl font-black">API e Webhooks</h1><p className="muted mt-2 max-w-3xl">Integre sistemas externos com escopos, quotas e entregas assinadas. Segredos completos são mostrados apenas no momento da criação.</p></div><div className="flex flex-wrap gap-2"><Link href="/desenvolvedores/receitas" className="btn-secondary">Receitas Zapier/Make/n8n</Link><Link href="/integracoes" className="btn-secondary">Outras integrações</Link></div></div>
    {status?<p className="mt-5 rounded-xl bg-emerald-50 p-4 text-sm font-semibold">Alteração concluída.</p>:null}{error?<p className="mt-5 rounded-xl bg-amber-50 p-4 text-sm">Não foi possível concluir a operação. Revise o status/endpoint e tente novamente.</p>:null}

    <section className="mt-8"><h2 className="text-xl font-black">API pública</h2>{!apiAllowed?<div className="card mt-4 p-6"><p className="font-bold">API pública não incluída no plano atual.</p><Link href="/assinatura?recurso=public_api" className="btn-primary mt-4">Ver planos</Link></div>:<>
      <div className="mt-4 grid gap-4 sm:grid-cols-3"><article className="card p-5"><p className="muted text-sm">Requisições — 24h</p><p className="mt-2 text-3xl font-black">{usage?.last_24h??0}</p></article><article className="card p-5"><p className="muted text-sm">Erros — 24h</p><p className="mt-2 text-3xl font-black">{usage?.errors_24h??0}</p></article><article className="card p-5"><p className="muted text-sm">Chaves ativas</p><p className="mt-2 text-3xl font-black">{usage?.active_keys??0}</p></article></div>
      {canManage?<div className="mt-4"><ApiKeyForm/></div>:null}
      <div className="card mt-4 overflow-x-auto"><table className="w-full min-w-[900px] text-left"><thead><tr className="border-b border-black/5">{["Nome","Prefixo","Escopos","Último uso","Expiração","Status","Controle"].map(h=><th className="p-4 text-sm" key={h}>{h}</th>)}</tr></thead><tbody>{keys.map(key=><tr className="border-b border-black/5 last:border-0" key={key.id}><td className="p-4 font-semibold">{key.name}</td><td className="p-4"><code className="text-xs">{key.key_prefix}…</code></td><td className="p-4 text-xs">{key.scopes.join(", ")}</td><td className="p-4 text-sm">{key.last_used_at?formatDate(key.last_used_at):"Nunca"}</td><td className="p-4 text-sm">{key.expires_at?formatDate(key.expires_at):"Sem expiração"}</td><td className="p-4 text-sm font-semibold">{key.status}</td><td className="p-4">{key.status==="active"&&canManage?<form action={revokeApiKeyAction}><input type="hidden" name="id" value={key.id}/><button className="btn-secondary min-h-10" type="submit">Revogar</button></form>:"—"}</td></tr>)}{keys.length===0?<tr><td className="p-6 text-sm muted" colSpan={7}>Nenhuma chave criada.</td></tr>:null}</tbody></table></div>
      <div className="card mt-4 p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h3 className="font-black">Contrato da API v1</h3><p className="muted mt-1 text-xs">OpenAPI 3.1 versionado para importar em Postman, Insomnia, SDK generators e documentação interna.</p></div><a href="/api/v1/openapi.json" className="btn-secondary" target="_blank" rel="noreferrer">Abrir OpenAPI JSON</a></div><pre className="mt-3 overflow-x-auto rounded-xl bg-black/[.04] p-4 text-xs">{`GET  /api/v1/leads        scope: leads:read\nPOST /api/v1/leads        scope: leads:write\nGET  /api/v1/customers    scope: customers:read\nGET  /api/v1/quotes       scope: quotes:read\n\nAuthorization: Bearer nd_live_...`}</pre><p className="muted mt-3 text-xs">Respostas incluem X-Request-Id e cabeçalhos de quota. A API não habilita CORS amplo por padrão; foi desenhada para integrações servidor-servidor.</p></div>
      {canManage?<><h3 className="mt-6 font-black">Últimas requisições</h3><p className="muted mt-1 text-xs">O log contém somente metadados operacionais. Corpo, Authorization, IP, chave completa e dados retornados não são persistidos aqui.</p><div className="card mt-3 overflow-x-auto"><table className="w-full min-w-[950px] text-left"><thead><tr className="border-b border-black/5">{["Data","Chave","Método","Rota","Escopo","HTTP","Duração","Request ID"].map(h=><th className="p-4 text-sm" key={h}>{h}</th>)}</tr></thead><tbody>{logs.map(item=><tr className="border-b border-black/5 last:border-0" key={item.id}><td className="p-4 text-sm">{formatDate(item.created_at)}</td><td className="p-4"><code className="text-xs">{item.key_prefix}…</code></td><td className="p-4 text-xs font-bold">{item.method}</td><td className="p-4 text-xs">{item.route}</td><td className="p-4 text-xs">{item.scope}</td><td className="p-4 text-sm">{item.response_status}</td><td className="p-4 text-sm">{item.duration_ms==null?"—":`${item.duration_ms} ms`}</td><td className="p-4"><code className="text-xs">{item.request_id??"—"}</code></td></tr>)}{logs.length===0?<tr><td className="p-6 text-sm muted" colSpan={8}>Nenhuma requisição registrada.</td></tr>:null}</tbody></table></div></>:null}
    </>}</section>

    <section className="mt-10"><h2 className="text-xl font-black">Webhooks outbound</h2>{!webhooksAllowed?<div className="card mt-4 p-6"><p className="font-bold">Webhooks para clientes não estão no plano atual.</p><Link href="/assinatura?recurso=outbound_webhooks" className="btn-primary mt-4">Ver planos</Link></div>:<>
      {canManage?<div className="mt-4"><WebhookForm/></div>:null}
      <div className="card mt-4 overflow-x-auto"><table className="w-full min-w-[1000px] text-left"><thead><tr className="border-b border-black/5">{["Endpoint","URL","Eventos","Segredo","Último sucesso","Status","Controle"].map(h=><th className="p-4 text-sm" key={h}>{h}</th>)}</tr></thead><tbody>{endpoints.map(endpoint=><tr className="border-b border-black/5 last:border-0" key={endpoint.id}><td className="p-4 font-semibold">{endpoint.name}</td><td className="p-4 text-xs break-all">{endpoint.url}</td><td className="p-4 text-xs">{endpoint.event_types.join(", ")}</td><td className="p-4"><code className="text-xs">{endpoint.signing_secret_prefix}…</code></td><td className="p-4 text-sm">{endpoint.last_success_at?formatDate(endpoint.last_success_at):"Nunca"}</td><td className="p-4 text-sm font-semibold">{endpoint.status}</td><td className="p-4">{canManage?<form action={setWebhookEndpointStatusAction} className="flex gap-2"><input type="hidden" name="id" value={endpoint.id}/><select name="status" defaultValue={endpoint.status} className="min-h-10 rounded-lg border border-black/10 bg-white px-2 text-sm"><option value="active">Ativo</option><option value="paused">Pausado</option><option value="disabled">Desativado</option></select><button className="btn-secondary min-h-10" type="submit">Aplicar</button></form>:"—"}</td></tr>)}{endpoints.length===0?<tr><td className="p-6 text-sm muted" colSpan={7}>Nenhum endpoint configurado.</td></tr>:null}</tbody></table></div>
      <h3 className="mt-6 font-black">Últimas entregas</h3><div className="card mt-3 overflow-x-auto"><table className="w-full min-w-[1000px] text-left"><thead><tr className="border-b border-black/5">{["Endpoint","Evento","Status","Tentativas","HTTP","Data","Erro","Ação"].map(h=><th className="p-4 text-sm" key={h}>{h}</th>)}</tr></thead><tbody>{deliveries.map(item=><tr className="border-b border-black/5 last:border-0" key={item.id}><td className="p-4 text-sm font-semibold">{item.endpoint_name}</td><td className="p-4 text-xs">{item.event_type}</td><td className="p-4 text-sm">{item.status}</td><td className="p-4 text-sm">{item.attempts}</td><td className="p-4 text-sm">{item.response_status??"—"}</td><td className="p-4 text-sm">{formatDate(item.created_at)}</td><td className="p-4 text-xs max-w-sm truncate" title={item.last_error??""}>{item.last_error??"—"}</td><td className="p-4">{item.status==="failed"&&canManage?<form action={retryWebhookDeliveryAction}><input type="hidden" name="id" value={item.id}/><button className="btn-secondary min-h-10" type="submit">Reenfileirar</button></form>:"—"}</td></tr>)}{deliveries.length===0?<tr><td className="p-6 text-sm muted" colSpan={8}>Nenhuma entrega registrada.</td></tr>:null}</tbody></table></div>
      <div className="card mt-4 p-5"><h3 className="font-black">Assinatura</h3><pre className="mt-3 overflow-x-auto rounded-xl bg-black/[.04] p-4 text-xs">{`X-ND-Event: lead_created\nX-ND-Delivery: <uuid>\nX-ND-Timestamp: <unix_seconds>\nX-ND-Signature: v1=<hex_hmac_sha256>\nIdempotency-Key: <delivery_uuid>\n\nassinatura = HMAC_SHA256(secret, timestamp + "." + raw_body)`}</pre><p className="muted mt-3 text-xs">Retry manual só é permitido após falha definitiva (dead letter). Ele reutiliza a mesma entrega e a mesma chave de idempotência.</p></div>
    </>}</section>
  </main></>;
}
