"use server";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { requireUser } from "@/lib/auth/require-user";
import { requireCurrentOrganization } from "@/lib/organizations/current";
import { getFeatureLimit,requireFeature } from "@/lib/plans/entitlements";
import { createAdminClient } from "@/lib/supabase/admin";
function field(fd:FormData,key:string,max=500){const raw=fd.get(key);return typeof raw==="string"?raw.trim().slice(0,max):"";}
async function context(){await requireFeature("multi_unit");const user=await requireUser();const organization=await requireCurrentOrganization();if(!["owner","admin"].includes(organization.role))redirect("/unidades?erro=permissao");return{user,organization,admin:createAdminClient()};}
export async function saveUnitAction(fd:FormData){const{user,organization,admin}=await context();const id=field(fd,"id",80)||null;const name=field(fd,"name",120);const code=field(fd,"code",20).toUpperCase().replace(/[^A-Z0-9_-]/g,"");const state=field(fd,"state",2).toUpperCase();const timezone=field(fd,"timezone",80)||"America/Sao_Paulo";if(name.length<2||!/^[A-Z0-9_-]{2,20}$/.test(code)||(state&&state.length!==2))redirect("/unidades?erro=campos");if(!id){const limit=(await getFeatureLimit("units"))??5;const{count}=await admin.from("organization_units").select("id",{count:"exact",head:true}).eq("organization_id",organization.id).eq("status","active");if((count??0)>=Math.max(limit,1))redirect("/unidades?erro=limite");}const email=field(fd,"email",254).toLowerCase();if(email&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))redirect("/unidades?erro=email");const active=fd.get("active")==="on";const row={organization_id:organization.id,name,code,phone:field(fd,"phone",40)||null,email:email||null,address:field(fd,"address",500)||null,city:field(fd,"city",120)||null,state:state||null,timezone,status:active?"active":"inactive",is_headquarters:active&&fd.get("is_headquarters")==="on",created_by:user.id};if(row.is_headquarters)await admin.from("organization_units").update({is_headquarters:false}).eq("organization_id",organization.id);const result=id?await admin.from("organization_units").update(row).eq("id",id).eq("organization_id",organization.id).select("id").single():await admin.from("organization_units").insert(row).select("id").single();if(result.error)redirect("/unidades?erro=salvar");await admin.from("audit_logs").insert({organization_id:organization.id,actor_user_id:user.id,action:id?"enterprise.unit_updated":"enterprise.unit_created",entity_type:"organization_unit",entity_id:result.data.id,metadata:{name,code}});revalidatePath("/unidades");redirect("/unidades?status=salvo");}
export async function assignUnitMemberAction(fd:FormData){const{user,organization,admin}=await context();const unitId=field(fd,"unit_id",80);const userId=field(fd,"user_id",80);const enabled=fd.get("enabled")==="on";const{data:unit}=await admin.from("organization_units").select("id").eq("id",unitId).eq("organization_id",organization.id).maybeSingle();const{data:member}=await admin.from("organization_members").select("user_id").eq("organization_id",organization.id).eq("user_id",userId).eq("status","active").maybeSingle();if(!unit||!member)redirect("/unidades?erro=vinculo");if(enabled)await admin.from("organization_member_units").upsert({organization_id:organization.id,user_id:userId,unit_id:unitId,created_by:user.id},{onConflict:"organization_id,user_id,unit_id"});else await admin.from("organization_member_units").delete().eq("organization_id",organization.id).eq("user_id",userId).eq("unit_id",unitId);await admin.from("audit_logs").insert({organization_id:organization.id,actor_user_id:user.id,action:enabled?"enterprise.unit_member_added":"enterprise.unit_member_removed",entity_type:"organization_unit",entity_id:unitId,metadata:{user_id:userId}});revalidatePath("/unidades");redirect("/unidades?status=vinculo");}
