import Link from "next/link";
import { DashboardNav } from "@/components/dashboard/nav";
import { createAppointmentAction, saveBookingSettingsAction, updateAppointmentStatusAction } from "@/features/appointments/actions";
import { requireUser } from "@/lib/auth/require-user";
import { requireCurrentOrganization } from "@/lib/organizations/current";
import { requireFeature } from "@/lib/plans/entitlements";
import { createClient } from "@/lib/supabase/server";

export const dynamic="force-dynamic";
type Props={searchParams:Promise<Record<string,string|string[]|undefined>>};
type Member={user_id:string;full_name:string|null;email:string|null;status:string};
type Appointment={id:string;starts_at:string;ends_at:string;status:string;source:string;professional_user_id:string|null;contact_name:string|null;services:{name:string}|{name:string}[]|null;leads:{name:string}|{name:string}[]|null;customers:{name:string}|{name:string}[]|null};
const days=[[1,"Segunda"],[2,"Terça"],[3,"Quarta"],[4,"Quinta"],[5,"Sexta"],[6,"Sábado"],[7,"Domingo"]] as const;
const first=<T,>(v:T|T[]|null)=>Array.isArray(v)?v[0]??null:v;

export default async function AgendaPage({searchParams}:Props){
  await requireUser(); await requireFeature("appointments"); const organization=await requireCurrentOrganization(); const supabase=await createClient(); const params=await searchParams;
  const [{data:settings},{data:services},{data:leads},{data:customers},{data:appointments},{data:membersData},{data:orgData}]=await Promise.all([
    supabase.from("booking_settings").select("enabled,slot_duration_minutes,buffer_minutes,availability").eq("organization_id",organization.id).maybeSingle(),
    supabase.from("services").select("id,name,duration_minutes").eq("organization_id",organization.id).eq("active",true).order("name"),
    supabase.from("leads").select("id,name").eq("organization_id",organization.id).not("status","in","(won,lost)").order("created_at",{ascending:false}).limit(100),
    supabase.from("customers").select("id,name").eq("organization_id",organization.id).order("created_at",{ascending:false}).limit(100),
    supabase.from("appointments").select("id,starts_at,ends_at,status,source,professional_user_id,contact_name,services(name),leads(name),customers(name)").eq("organization_id",organization.id).gte("ends_at",new Date(Date.now()-86400000).toISOString()).order("starts_at").limit(200),
    supabase.rpc("organization_member_directory",{p_organization_id:organization.id}),
    supabase.from("organizations").select("timezone").eq("id",organization.id).single()
  ]);
  const members=((membersData??[]) as Member[]).filter(m=>m.status==="active"); const timeZone=orgData?.timezone||"America/Sao_Paulo"; const availability=(settings?.availability??{}) as Record<string,string[][]>; const status=typeof params.status==="string"?params.status:""; const error=typeof params.erro==="string"?params.erro:""; const canManage=["owner","admin"].includes(organization.role);
  return <><DashboardNav organizationName={organization.name}/><main className="container-shell py-10"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-bold uppercase tracking-widest text-blue-700">Agenda</p><h1 className="mt-1 text-3xl font-black">Agendamentos</h1><p className="muted mt-2">Horários reais, com timezone da organização e bloqueio de conflito para profissional selecionado.</p></div><div className="flex flex-wrap gap-2"><Link href="/agenda/calendario" className="btn-secondary">Ver calendário</Link>{settings?.enabled?<Link href={`/agendar/${organization.slug}`} className="btn-secondary">Abrir página pública</Link>:null}</div></div>{status?<p className="mt-5 rounded-xl bg-emerald-50 p-4 text-sm font-semibold">Alteração concluída.</p>:null}{error?<p className="mt-5 rounded-xl bg-amber-50 p-4 text-sm">{error==="conflito"?"O profissional já possui compromisso nesse horário.":error==="horario"?"Revise os horários de disponibilidade.":"Não foi possível concluir a operação."}</p>:null}
  <section className="card mt-7 p-6"><h2 className="text-xl font-black">Novo agendamento interno</h2><form action={createAppointmentAction} className="mt-4 grid gap-4 lg:grid-cols-3"><label className="field"><span>Data e hora</span><input type="datetime-local" name="start" required/></label><label className="field"><span>Serviço</span><select name="service_id" defaultValue=""><option value="">Sem serviço</option>{(services??[]).map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label className="field"><span>Profissional</span><select name="professional_user_id" defaultValue=""><option value="">Não atribuído</option>{members.map(m=><option key={m.user_id} value={m.user_id}>{m.full_name||m.email||"Usuário"}</option>)}</select></label><label className="field"><span>Lead</span><select name="lead_id" defaultValue=""><option value="">Nenhum</option>{(leads??[]).map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select></label><label className="field"><span>Cliente</span><select name="customer_id" defaultValue=""><option value="">Nenhum</option>{(customers??[]).map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label className="field"><span>Duração (min)</span><input type="number" name="duration_minutes" min="15" max="480" placeholder="Usa a duração do serviço"/></label><label className="field lg:col-span-3"><span>Observações</span><textarea name="notes" maxLength={2000}/></label><button className="btn-primary lg:col-span-3 lg:justify-self-start" type="submit">Adicionar à agenda</button></form></section>
  {canManage?<section className="card mt-6 p-6"><h2 className="text-xl font-black">Agendamento público</h2><p className="muted mt-1 text-sm">Configure uma janela por dia. A V1 pública bloqueia o horário para a empresa inteira, evitando dupla reserva.</p><form action={saveBookingSettingsAction} className="mt-4 grid gap-4"><div className="grid gap-4 sm:grid-cols-3"><label className="field"><span>Duração padrão</span><input type="number" name="slot_duration_minutes" min="15" max="480" defaultValue={settings?.slot_duration_minutes??60}/></label><label className="field"><span>Intervalo</span><input type="number" name="buffer_minutes" min="0" max="180" defaultValue={settings?.buffer_minutes??0}/></label><label className="self-end pb-3"><input type="checkbox" name="enabled" defaultChecked={settings?.enabled===true}/> Aceitar agendamentos pelo site</label></div><div className="grid gap-3">{days.map(([day,label])=>{const range=availability[String(day)]?.[0];return <div key={day} className="grid gap-2 rounded-xl border border-black/10 p-3 sm:grid-cols-[180px_1fr_1fr]"><label className="self-center font-semibold"><input type="checkbox" name={`day_${day}_enabled`} defaultChecked={Boolean(range)}/> {label}</label><label className="field"><span>Abre</span><input type="time" name={`day_${day}_start`} defaultValue={range?.[0]??"08:00"}/></label><label className="field"><span>Fecha</span><input type="time" name={`day_${day}_end`} defaultValue={range?.[1]??"18:00"}/></label></div>})}</div><button className="btn-secondary justify-self-start" type="submit">Salvar disponibilidade</button></form></section>:null}
  <section className="mt-8"><h2 className="text-xl font-black">Próximos compromissos</h2><div className="mt-4 grid gap-3">{((appointments??[]) as Appointment[]).map(a=>{const service=first(a.services);const lead=first(a.leads);const customer=first(a.customers);const professional=members.find(m=>m.user_id===a.professional_user_id);return <article key={a.id} className="card grid gap-4 p-5 lg:grid-cols-[1fr_auto] lg:items-center"><div><p className="font-black">{customer?.name||lead?.name||a.contact_name||"Contato"}</p><p className="muted mt-1 text-sm">{new Intl.DateTimeFormat("pt-BR",{dateStyle:"medium",timeStyle:"short",timeZone}).format(new Date(a.starts_at))} → {new Intl.DateTimeFormat("pt-BR",{timeStyle:"short",timeZone}).format(new Date(a.ends_at))}</p><p className="mt-2 text-sm">{service?.name||"Sem serviço"} · {professional?.full_name||professional?.email||"Não atribuído"} · {a.source==="public"?"Site":"Interno"}</p></div><form action={updateAppointmentStatusAction} className="flex gap-2"><input type="hidden" name="appointment_id" value={a.id}/><select name="status" defaultValue={a.status} className="rounded-lg border border-black/10 bg-white px-3"><option value="scheduled">Agendado</option><option value="confirmed">Confirmado</option><option value="completed">Concluído</option><option value="canceled">Cancelado</option><option value="no_show">Não compareceu</option></select><button className="btn-secondary" type="submit">Salvar</button></form></article>})}{(appointments??[]).length===0?<div className="card p-6"><p className="font-semibold">Nenhum compromisso próximo.</p><p className="muted mt-1 text-sm">Crie um agendamento acima ou ative a página pública.</p></div>:null}</div></section></main></>;
}
