import Link from "next/link";
import { DashboardNav } from "@/components/dashboard/nav";
import { formatMoney } from "@/lib/format";
import { requireCurrentOrganization } from "@/lib/organizations/current";
import { requireFeature } from "@/lib/plans/entitlements";
import { createClient } from "@/lib/supabase/server";

type Row={label:string;count:number};
type Daily={date:string;visits:number;leads:number;quotes:number;sales_cents:number};
type TopItem={type:string;description:string;quantity:number;revenue_cents:number};
type Summary={days:number;timezone:string;visitors:number;page_views:number;leads:number;site_leads:number;previous_leads:number;customers:number;quotes:number;approved_quotes:number;sales_cents:number;previous_sales_cents:number;average_ticket_cents:number;appointments:number|null;lead_sources:Row[];utm_sources:Row[];utm_mediums:Row[];top_items:TopItem[];daily:Daily[]};

function pct(part:number,total:number){return total>0?`${((part/total)*100).toFixed(1).replace(".",",")}%`:"—";}
function delta(current:number,previous:number){if(previous===0)return current>0?"Novo período":"0%";const value=((current-previous)/previous)*100;return `${value>=0?"+":""}${value.toFixed(1).replace(".",",")}%`;}
function maxOf(values:number[]){return Math.max(1,...values);}
function MiniBars({rows}:{rows:Row[]}){const max=maxOf(rows.map(r=>r.count));return <div className="grid gap-3">{rows.length?rows.map(row=><div key={row.label}><div className="mb-1 flex justify-between gap-3 text-sm"><span className="truncate font-semibold">{row.label}</span><span>{row.count}</span></div><div className="h-2 overflow-hidden rounded-full bg-black/5"><div className="h-full rounded-full bg-black/70" style={{width:`${Math.max(3,(row.count/max)*100)}%`}}/></div></div>):<p className="muted text-sm">Ainda não há dados neste período.</p>}</div>}

export default async function AnalyticsPage({searchParams}:{searchParams:Promise<Record<string,string|string[]|undefined>>}){
  await requireFeature("analytics");const organization=await requireCurrentOrganization();const query=await searchParams;const raw=typeof query.periodo==="string"?Number(query.periodo):30;const days=Number.isInteger(raw)&&raw>=7&&raw<=365?raw:30;const supabase=await createClient();
  const {data,error}=await supabase.rpc("organization_analytics_summary",{p_organization_id:organization.id,p_days:days});
  if(error)throw new Error(`Falha ao carregar analytics: ${error.message}`);const s=(data??{}) as Summary;const daily=s.daily??[];const maxDaily=maxOf(daily.map(d=>Math.max(d.visits,d.leads,d.quotes)));
  return <><DashboardNav organizationName={organization.name}/><main className="container-shell py-10"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-bold uppercase tracking-widest text-blue-700">Analytics</p><h1 className="mt-1 text-3xl font-black">Resultados do negócio</h1><p className="muted mt-2">Somente dados reais registrados pela sua operação. Período de {days} dias.</p></div><div className="flex flex-wrap gap-2">{[7,30,90].map(period=><Link key={period} href={`/analytics?periodo=${period}`} className={period===days?"btn-primary":"btn-secondary"}>{period} dias</Link>)}<form method="get" className="flex gap-2"><label className="sr-only" htmlFor="periodo-custom">Período personalizado</label><input id="periodo-custom" name="periodo" type="number" min="7" max="365" defaultValue={days} className="w-24 rounded-xl border border-black/10 px-3 text-sm"/><button className="btn-secondary" type="submit">Aplicar</button></form></div></div>
  <section className="mt-7 grid gap-4 sm:grid-cols-2 xl:grid-cols-5"><div className="card p-5"><p className="muted text-sm">Visitantes</p><p className="mt-2 text-3xl font-black">{s.visitors??0}</p><p className="muted mt-1 text-xs">{s.page_views??0} visualizações</p></div><div className="card p-5"><p className="muted text-sm">Leads</p><p className="mt-2 text-3xl font-black">{s.leads??0}</p><p className="mt-1 text-xs font-semibold">{delta(s.leads??0,s.previous_leads??0)} vs. período anterior</p></div><div className="card p-5"><p className="muted text-sm">Conversão site → lead</p><p className="mt-2 text-3xl font-black">{pct(s.site_leads??0,s.visitors??0)}</p><p className="muted mt-1 text-xs">Sem promessa de resultado</p></div><div className="card p-5"><p className="muted text-sm">Orçamentos aprovados</p><p className="mt-2 text-3xl font-black">{s.approved_quotes??0}</p><p className="muted mt-1 text-xs">{pct(s.approved_quotes??0,s.quotes??0)} dos orçamentos</p></div><div className="card p-5"><p className="muted text-sm">Valor aprovado</p><p className="mt-2 text-2xl font-black">{formatMoney(s.sales_cents??0)}</p><p className="mt-1 text-xs font-semibold">{delta(s.sales_cents??0,s.previous_sales_cents??0)} vs. período anterior</p></div></section>
  <section className="mt-8 grid gap-5 lg:grid-cols-[1.35fr_.65fr]"><div className="card p-6"><div className="flex items-end justify-between gap-3"><div><h2 className="text-xl font-black">Evolução diária</h2><p className="muted mt-1 text-sm">Visitas, leads e orçamentos por dia.</p></div><div className="text-right text-sm"><p><strong>{formatMoney(s.average_ticket_cents??0)}</strong></p><p className="muted text-xs">ticket médio aprovado</p></div></div><div className="mt-6 flex h-52 items-end gap-1 overflow-x-auto border-b border-black/10 pb-1" aria-label="Evolução diária">{daily.map(d=><div key={d.date} className="flex min-w-7 flex-1 items-end justify-center gap-[2px]" title={`${d.date}: ${d.visits} visitas, ${d.leads} leads, ${d.quotes} orçamentos`}><div className="w-1.5 rounded-t bg-black/20" style={{height:`${Math.max(2,(d.visits/maxDaily)*100)}%`}}/><div className="w-1.5 rounded-t bg-black/55" style={{height:`${Math.max(2,(d.leads/maxDaily)*100)}%`}}/><div className="w-1.5 rounded-t bg-black/85" style={{height:`${Math.max(2,(d.quotes/maxDaily)*100)}%`}}/></div>)}</div><div className="mt-3 flex flex-wrap gap-4 text-xs"><span>▰ Visitas</span><span>▰ Leads</span><span>▰ Orçamentos</span></div></div><div className="card p-6"><h2 className="text-xl font-black">Funil</h2><div className="mt-5 grid gap-3">{[["Visitantes",s.visitors??0],["Leads do site",s.site_leads??0],["Orçamentos",s.quotes??0],["Aprovados",s.approved_quotes??0]].map(([label,value])=><div key={String(label)} className="flex items-center justify-between rounded-xl border border-black/5 px-4 py-3"><span className="font-semibold">{label}</span><strong>{value}</strong></div>)}</div>{s.appointments!=null?<p className="muted mt-4 text-sm">Agendamentos criados: <strong className="text-black">{s.appointments}</strong></p>:null}<p className="muted mt-2 text-sm">Clientes cadastrados no período: <strong className="text-black">{s.customers??0}</strong></p></div></section>
  <section className="mt-8 grid gap-5 lg:grid-cols-3"><div className="card p-6"><h2 className="text-lg font-black">Origem dos leads</h2><div className="mt-5"><MiniBars rows={s.lead_sources??[]}/></div></div><div className="card p-6"><h2 className="text-lg font-black">UTM source</h2><div className="mt-5"><MiniBars rows={s.utm_sources??[]}/></div></div><div className="card p-6"><h2 className="text-lg font-black">Canais / UTM medium</h2><div className="mt-5"><MiniBars rows={s.utm_mediums??[]}/></div></div></section>
  <section className="mt-8"><h2 className="text-xl font-black">Itens com maior valor aprovado</h2><div className="card mt-4 overflow-x-auto"><table className="w-full min-w-[680px] text-left"><thead><tr className="border-b border-black/5"><th className="p-4">Item</th><th className="p-4">Tipo</th><th className="p-4">Quantidade</th><th className="p-4">Valor aprovado</th></tr></thead><tbody>{(s.top_items??[]).map((item,index)=><tr key={`${item.type}-${item.description}-${index}`} className="border-b border-black/5 last:border-0"><td className="p-4 font-semibold">{item.description}</td><td className="p-4 text-sm">{item.type==="service"?"Serviço":item.type==="product"?"Produto":"Personalizado"}</td><td className="p-4 text-sm">{Number(item.quantity).toLocaleString("pt-BR")}</td><td className="p-4 font-semibold">{formatMoney(item.revenue_cents)}</td></tr>)}{!(s.top_items??[]).length?<tr><td colSpan={4} className="p-6 text-sm muted">Nenhum orçamento aprovado no período.</td></tr>:null}</tbody></table></div></section>
  </main></>;
}
