"use server";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { requireUser } from "@/lib/auth/require-user";
import { requireCurrentOrganization } from "@/lib/organizations/current";
import { getFeatureLimit,requireFeature } from "@/lib/plans/entitlements";
import { createAdminClient } from "@/lib/supabase/admin";
import { addVercelDomain,normalizeCustomDomain,removeVercelDomain,safeVercelDomainData,verifyVercelDomain,vercelDomainsConfigured } from "@/lib/white-label/vercel-domains";
function field(fd:FormData,key:string,max=1000){const raw=fd.get(key);return typeof raw==="string"?raw.trim().slice(0,max):"";}
async function context(){await requireFeature("white_label");const user=await requireUser();const organization=await requireCurrentOrganization();if(!["owner","admin"].includes(organization.role))redirect("/white-label?erro=permissao");return{user,organization,admin:createAdminClient()};}
function safeHttps(value:string){if(!value)return null;try{const url=new URL(value);return url.protocol==="https:"?url.toString().slice(0,1000):null;}catch{return null;}}
export async function saveBrandingAction(fd:FormData){const{user,organization,admin}=await context();const brandName=field(fd,"brand_name",100);const logoUrl=safeHttps(field(fd,"logo_url",1000));const faviconUrl=safeHttps(field(fd,"favicon_url",1000));const primary=field(fd,"primary_color",7);const support=field(fd,"support_email",254).toLowerCase();if(brandName&&brandName.length<2)redirect("/white-label?erro=marca");if(primary&&!/^#[0-9a-f]{6}$/i.test(primary))redirect("/white-label?erro=cor");if(support&&!/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(support))redirect("/white-label?erro=email");const{error}=await admin.from("organization_branding").upsert({organization_id:organization.id,brand_name:brandName||null,logo_url:logoUrl,favicon_url:faviconUrl,primary_color:primary||null,support_email:support||null,hide_platform_branding:fd.get("hide_platform_branding")==="on",updated_by:user.id},{onConflict:"organization_id"});if(error)redirect("/white-label?erro=salvar");await admin.from("audit_logs").insert({organization_id:organization.id,actor_user_id:user.id,action:"white_label.branding_updated",entity_type:"organization",entity_id:organization.id});revalidatePath("/white-label");revalidatePath(`/empresa/${organization.slug}`);redirect("/white-label?status=marca-salva");}
export async function addCustomDomainAction(fd:FormData){const{user,organization,admin}=await context();if(!vercelDomainsConfigured())redirect("/white-label?erro=vercel_nao_configurada");let hostname:string;try{hostname=normalizeCustomDomain(field(fd,"hostname",260));}catch{redirect("/white-label?erro=dominio");throw new Error();}const limit=(await getFeatureLimit("custom_domains"))??1;const{count}=await admin.from("custom_domains").select("id",{count:"exact",head:true}).eq("organization_id",organization.id).neq("status","disabled");if((count??0)>=Math.max(limit,1))redirect("/white-label?erro=limite");const{data:created,error}=await admin.from("custom_domains").insert({organization_id:organization.id,hostname,status:"pending",created_by:user.id}).select("id").single();if(error||!created)redirect("/white-label?erro=dominio_em_uso");try{const provider=await addVercelDomain(hostname);const safe=safeVercelDomainData(provider);await admin.from("custom_domains").update({status:safe.verified?"active":"verifying",provider_verified:safe.verified,provider_data:safe,last_checked_at:new Date().toISOString(),last_error:null}).eq("id",created.id);await admin.from("audit_logs").insert({organization_id:organization.id,actor_user_id:user.id,action:"white_label.domain_added",entity_type:"custom_domain",entity_id:created.id,metadata:{hostname,verified:safe.verified}});}catch(error){await admin.from("custom_domains").update({status:"error",last_checked_at:new Date().toISOString(),last_error:(error instanceof Error?error.message:"provider error").slice(0,500)}).eq("id",created.id);redirect("/white-label?erro=vercel");}revalidatePath("/white-label");redirect("/white-label?status=dominio-adicionado");}
export async function verifyCustomDomainAction(fd:FormData){const{user,organization,admin}=await context();if(!vercelDomainsConfigured())redirect("/white-label?erro=vercel_nao_configurada");const id=field(fd,"id",80);const{data:domain}=await admin.from("custom_domains").select("hostname").eq("id",id).eq("organization_id",organization.id).neq("status","disabled").maybeSingle();if(!domain)redirect("/white-label?erro=dominio");try{const provider=await verifyVercelDomain(domain.hostname);const safe=safeVercelDomainData(provider);await admin.from("custom_domains").update({status:safe.verified?"active":"verifying",provider_verified:safe.verified,provider_data:safe,last_checked_at:new Date().toISOString(),last_error:safe.verified?null:"Aguardando configuração DNS"}).eq("id",id);if(safe.verified){const{count}=await admin.from("custom_domains").select("id",{count:"exact",head:true}).eq("organization_id",organization.id).eq("status","active").eq("is_primary",true);if((count??0)===0)await admin.from("custom_domains").update({is_primary:true}).eq("id",id);}await admin.from("audit_logs").insert({organization_id:organization.id,actor_user_id:user.id,action:"white_label.domain_verified",entity_type:"custom_domain",entity_id:id,metadata:{hostname:domain.hostname,verified:safe.verified}});}catch(error){await admin.from("custom_domains").update({status:"verifying",last_checked_at:new Date().toISOString(),last_error:(error instanceof Error?error.message:"verification failed").slice(0,500)}).eq("id",id);redirect("/white-label?erro=verificacao");}revalidatePath("/white-label");redirect("/white-label?status=dominio-verificado");}
export async function setPrimaryDomainAction(fd:FormData){const{user,organization,admin}=await context();const id=field(fd,"id",80);const{data}=await admin.from("custom_domains").select("id").eq("id",id).eq("organization_id",organization.id).eq("status","active").eq("provider_verified",true).maybeSingle();if(!data)redirect("/white-label?erro=dominio");await admin.from("custom_domains").update({is_primary:false}).eq("organization_id",organization.id);await admin.from("custom_domains").update({is_primary:true}).eq("id",id).eq("organization_id",organization.id);await admin.from("audit_logs").insert({organization_id:organization.id,actor_user_id:user.id,action:"white_label.primary_domain_changed",entity_type:"custom_domain",entity_id:id});revalidatePath("/white-label");revalidatePath(`/empresa/${organization.slug}`);redirect("/white-label?status=principal-alterado");}
export async function removeCustomDomainAction(fd:FormData){const{user,organization,admin}=await context();if(!vercelDomainsConfigured())redirect("/white-label?erro=vercel_nao_configurada");const id=field(fd,"id",80);const{data:domain}=await admin.from("custom_domains").select("hostname").eq("id",id).eq("organization_id",organization.id).neq("status","disabled").maybeSingle();if(!domain)redirect("/white-label?erro=dominio");try{await removeVercelDomain(domain.hostname);}catch{redirect("/white-label?erro=remover_vercel");}await admin.from("custom_domains").update({status:"disabled",provider_verified:false,is_primary:false,last_checked_at:new Date().toISOString(),last_error:null}).eq("id",id);await admin.from("audit_logs").insert({organization_id:organization.id,actor_user_id:user.id,action:"white_label.domain_removed",entity_type:"custom_domain",entity_id:id,metadata:{hostname:domain.hostname}});revalidatePath("/white-label");redirect("/white-label?status=dominio-removido");}
