"use client";
import {useActionState} from "react";
import {generateCopilotAction,generateCopyAction,generateInsightsAction,generateQuoteTextAction,type AIActionState} from "@/features/ai/actions";
const initial:AIActionState={output:"",error:""};
function Result({state}:{state:AIActionState}){return <>{state.error?<p className="mt-4 rounded-xl bg-amber-50 p-4 text-sm">{state.error}</p>:null}{state.output?<div className="mt-4 rounded-xl border border-black/10 bg-black/[.02] p-4"><p className="whitespace-pre-wrap text-sm leading-6">{state.output}</p><p className="muted mt-4 border-t border-black/5 pt-3 text-xs">Sugestão gerada por IA. Revise antes de usar ou enviar.</p></div>:null}</>}
export function CopilotForm(){const[state,action,pending]=useActionState(generateCopilotAction,initial);return <form action={action} className="card p-6"><h2 className="text-xl font-black">Copiloto do negócio</h2><p className="muted mt-1 text-sm">Pergunte sobre leads, orçamentos, tarefas e agenda usando os dados atuais da empresa.</p><label className="field mt-4"><span>Pergunta</span><textarea name="question" required maxLength={1800} placeholder="Quais clientes precisam de atenção hoje?"/></label><button className="btn-primary mt-4" disabled={pending}>{pending?"Analisando...":"Perguntar"}</button><Result state={state}/></form>}
export function CopyForm(){const[state,action,pending]=useActionState(generateCopyAction,initial);return <form action={action} className="card p-6"><h2 className="text-xl font-black">Textos com IA</h2><div className="mt-4 grid gap-4"><label className="field"><span>Tipo</span><select name="purpose" defaultValue="Descrição de serviço"><option>Descrição de empresa</option><option>Descrição de produto</option><option>Descrição de serviço</option><option>Texto para site</option><option>FAQ</option><option>Post</option></select></label><label className="field"><span>Briefing</span><textarea name="brief" required maxLength={5000} placeholder="Informe apenas fatos reais sobre o que deve aparecer no texto."/></label></div><button className="btn-primary mt-4" disabled={pending}>{pending?"Gerando...":"Gerar texto"}</button><Result state={state}/></form>}
export function QuoteAIForm(){const[state,action,pending]=useActionState(generateQuoteTextAction,initial);return <form action={action} className="card p-6"><h2 className="text-xl font-black">Apoio ao orçamento</h2><p className="muted mt-1 text-sm">A IA estrutura o texto; preços continuam vindo do usuário/banco.</p><label className="field mt-4"><span>Contexto</span><textarea name="brief" required maxLength={5000} placeholder="Ex.: manutenção preventiva com inspeção, troca de filtros e relatório final. Valor já definido: R$ ..."/></label><button className="btn-primary mt-4" disabled={pending}>{pending?"Gerando...":"Sugerir estrutura"}</button><Result state={state}/></form>}
export function InsightsForm(){const[state,action,pending]=useActionState(generateInsightsAction,initial);return <form action={action} className="card p-6"><h2 className="text-xl font-black">Resumo inteligente</h2><p className="muted mt-1 text-sm">Analisa os últimos 30 dias do Analytics e separa fatos de hipóteses.</p><button className="btn-primary mt-4" disabled={pending}>{pending?"Analisando...":"Gerar insights"}</button><Result state={state}/></form>}
