import Link from "next/link";
import { DashboardNav } from "@/components/dashboard/nav";
import { requireCurrentOrganization } from "@/lib/organizations/current";
import { requireFeature } from "@/lib/plans/entitlements";
import { createClient } from "@/lib/supabase/server";

type Appointment={id:string;starts_at:string;ends_at:string;status:string;source:string;name:string;service:string|null;professional:string|null};
type CalendarData={view:"day"|"week"|"month";timezone:string;anchor:string;start_date:string;end_date:string;appointments:Appointment[]};
const statusLabel:Record<string,string>={scheduled:"Agendado",confirmed:"Confirmado",completed:"Concluído",canceled:"Cancelado",no_show:"Não compareceu"};
function validDate(value:unknown){return typeof value==="string"&&/^\d{4}-\d{2}-\d{2}$/.test(value)?value:new Date().toISOString().slice(0,10);}
function shift(date:string,view:string,direction:number){const d=new Date(`${date}T12:00:00Z`);if(view==="day")d.setUTCDate(d.getUTCDate()+direction);else if(view==="week")d.setUTCDate(d.getUTCDate()+7*direction);else d.setUTCMonth(d.getUTCMonth()+direction);return d.toISOString().slice(0,10);}
function localDate(iso:string,tz:string){const parts=new Intl.DateTimeFormat("en-CA",{timeZone:tz,year:"numeric",month:"2-digit",day:"2-digit"}).formatToParts(new Date(iso));const get=(t:string)=>parts.find(p=>p.type===t)?.value??"";return `${get("year")}-${get("month")}-${get("day")}`;}
function time(iso:string,tz:string){return new Intl.DateTimeFormat("pt-BR",{timeZone:tz,hour:"2-digit",minute:"2-digit"}).format(new Date(iso));}
function dateLabel(date:string){return new Intl.DateTimeFormat("pt-BR",{dateStyle:"medium",timeZone:"UTC"}).format(new Date(`${date}T12:00:00Z`));}
function datesBetween(start:string,end:string){const list:string[]=[];for(let d=new Date(`${start}T12:00:00Z`),last=new Date(`${end}T12:00:00Z`);d<=last;d.setUTCDate(d.getUTCDate()+1))list.push(d.toISOString().slice(0,10));return list;}
function dayName(date:string){return new Intl.DateTimeFormat("pt-BR",{weekday:"short",timeZone:"UTC"}).format(new Date(`${date}T12:00:00Z`));}
export default async function CalendarPage({searchParams}:{searchParams:Promise<Record<string,string|string[]|undefined>>}){
  await requireFeature("appointments");const organization=await requireCurrentOrganization();const query=await searchParams;const view=typeof query.view==="string"&&["day","week","month"].includes(query.view)?query.view:"week";const date=validDate(query.date);const supabase=await createClient();const {data,error}=await supabase.rpc("appointments_calendar",{p_organization_id:organization.id,p_date:date,p_view:view});if(error)throw new Error(`Falha ao carregar calendário: ${error.message}`);const c=data as CalendarData;const appointments=c.appointments??[];const start=c.start_date;const end=c.end_date;const visibleDates=datesBetween(start,end);const monthStartWeekday=(new Date(`${start}T12:00:00Z`).getUTCDay()+6)%7;const monthCells=c.view==="month"?[...Array(monthStartWeekday).fill(null),...visibleDates]:visibleDates;
  return <><DashboardNav organizationName={organization.name}/><main className="container-shell py-10"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-bold uppercase tracking-widest text-blue-700">Agenda</p><h1 className="mt-1 text-3xl font-black">Calendário</h1><p className="muted mt-2">{dateLabel(start)} até {dateLabel(end)} · {c.timezone}</p></div><div className="flex flex-wrap gap-2"><Link href="/agenda" className="btn-secondary">Gerenciar agenda</Link>{["day","week","month"].map(v=><Link key={v} href={`/agenda/calendario?view=${v}&date=${date}`} className={v===c.view?"btn-primary":"btn-secondary"}>{v==="day"?"Dia":v==="week"?"Semana":"Mês"}</Link>)}</div></div><div className="mt-5 flex items-center justify-between"><Link className="btn-secondary" href={`/agenda/calendario?view=${c.view}&date=${shift(date,c.view,-1)}`}>← Anterior</Link><Link className="btn-secondary" href={`/agenda/calendario?view=${c.view}&date=${new Date().toISOString().slice(0,10)}`}>Hoje</Link><Link className="btn-secondary" href={`/agenda/calendario?view=${c.view}&date=${shift(date,c.view,1)}`}>Próximo →</Link></div>
  {c.view==="day"?<section className="mt-7 grid gap-3">{appointments.map(a=><article className="card p-5" key={a.id}><div className="flex flex-wrap justify-between gap-3"><div><p className="text-lg font-black">{a.name}</p><p className="muted mt-1 text-sm">{a.service||"Sem serviço"} · {a.professional||"Não atribuído"}</p></div><div className="text-right"><p className="font-black">{time(a.starts_at,c.timezone)}–{time(a.ends_at,c.timezone)}</p><p className="muted text-xs">{statusLabel[a.status]??a.status}</p></div></div></article>)}{!appointments.length?<div className="card p-6"><p className="muted text-sm">Nenhum compromisso neste dia.</p></div>:null}</section>:c.view==="week"?<section className="mt-7 grid gap-3 lg:grid-cols-7">{visibleDates.map(d=>{const list=appointments.filter(a=>localDate(a.starts_at,c.timezone)===d);return <div className="card min-h-52 p-3" key={d}><p className="text-xs font-bold uppercase">{dayName(d)}</p><p className="mt-1 font-black">{dateLabel(d)}</p><div className="mt-3 grid gap-2">{list.map(a=><div key={a.id} className="rounded-lg border border-black/10 p-2 text-xs"><p className="font-bold">{time(a.starts_at,c.timezone)} · {a.name}</p><p className="muted mt-1">{a.service||statusLabel[a.status]||a.status}</p></div>)}{!list.length?<p className="muted text-xs">Livre</p>:null}</div></div>})}</section>:<section className="mt-7"><div className="mb-2 grid grid-cols-7 gap-2 text-center text-xs font-bold uppercase">{["Seg","Ter","Qua","Qui","Sex","Sáb","Dom"].map(d=><span key={d}>{d}</span>)}</div><div className="grid grid-cols-7 gap-2">{monthCells.map((d,index)=>d===null?<div key={`empty-${index}`} className="min-h-24 rounded-xl bg-black/[.02]"/>:(()=>{const list=appointments.filter(a=>localDate(a.starts_at,c.timezone)===d);return <div className="card min-h-24 p-2" key={d}><p className="text-xs font-black">{Number(d.slice(-2))}</p><div className="mt-2 grid gap-1">{list.slice(0,3).map(a=><div key={a.id} title={`${a.name} · ${statusLabel[a.status]??a.status}`} className="truncate rounded bg-black/5 px-1.5 py-1 text-[11px]"><strong>{time(a.starts_at,c.timezone)}</strong> {a.name}</div>)}{list.length>3?<p className="text-[10px] font-semibold">+{list.length-3} compromissos</p>:null}</div></div>})())}</div></section>}
  </main></>;
}
