import Link from "next/link";
import { DashboardNav } from "@/components/dashboard/nav";
import { disconnectGoogleCalendarAction,disconnectWhatsAppAction,geocodeOrganizationAddressAction,saveWhatsAppConnectionAction,testWhatsAppConnectionAction } from "@/features/integrations/actions";
import { requireUser } from "@/lib/auth/require-user";
import { isTransactionalEmailConfigured } from "@/lib/communications/email";
import { isResendWebhookConfigured } from "@/lib/communications/resend-webhook";
import { isWhatsAppWebhookConfigured } from "@/lib/communications/whatsapp";
import { isGoogleCalendarConfigured } from "@/lib/integrations/google-calendar";
import { isGoogleMapsConfigured } from "@/lib/integrations/google-maps";
import { requireCurrentOrganization } from "@/lib/organizations/current";
import { hasFeature } from "@/lib/plans/entitlements";
import { createClient } from "@/lib/supabase/server";

export const dynamic="force-dynamic";
type Props={searchParams:Promise<Record<string,string|string[]|undefined>>};
type Connection={id:string;provider:string;status:string;config:Record<string,unknown>;last_verified_at:string|null;last_error:string|null};
function Badge({active,label}:{active:boolean;label:string}){return <span className={`rounded-full px-3 py-1 text-xs font-bold ${active?"bg-emerald-50 text-emerald-800":"bg-black/5"}`}>{label}</span>;}

export default async function IntegrationsPage({searchParams}:Props){
  await requireUser();const organization=await requireCurrentOrganization();const supabase=await createClient();
  const [emailAllowed,whatsappAllowed,calendarAllowed,mapsAllowed]=await Promise.all([hasFeature("email_transactional"),hasFeature("whatsapp_official"),hasFeature("google_calendar"),hasFeature("google_maps")]);
  const [{data:connections},{data:org}]=await Promise.all([
    supabase.from("integration_connections").select("id,provider,status,config,last_verified_at,last_error").eq("organization_id",organization.id).in("provider",["whatsapp_cloud","google_calendar"]),
    supabase.from("organizations").select("address,city,state,latitude,longitude,geocoded_address,geocoded_at").eq("id",organization.id).maybeSingle()
  ]);
  const list=(connections||[]) as Connection[];const whatsapp=list.find(c=>c.provider==="whatsapp_cloud")||null;const calendar=list.find(c=>c.provider==="google_calendar")||null;
  const params=await searchParams;const status=typeof params.status==="string"?params.status:"";const error=typeof params.erro==="string"?params.erro:"";const canManage=["owner","admin"].includes(organization.role);const appUrl=(process.env.NEXT_PUBLIC_APP_URL||"").replace(/\/$/,"");
  const waConfig=whatsapp?.config||{};const phone=typeof waConfig.display_phone_number==="string"?waConfig.display_phone_number:"";const verifiedName=typeof waConfig.verified_name==="string"?waConfig.verified_name:"";const quality=typeof waConfig.quality_rating==="string"?waConfig.quality_rating:"";const phoneId=typeof waConfig.phone_number_id==="string"?waConfig.phone_number_id:"";const wabaId=typeof waConfig.waba_id==="string"?waConfig.waba_id:"";
  const calendarEmail=typeof calendar?.config?.connected_email==="string"?calendar.config.connected_email:"";
  const mapsHref=typeof org?.latitude==="number"&&typeof org?.longitude==="number"?`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(`${org.latitude},${org.longitude}`)}`:null;
  return <><DashboardNav organizationName={organization.name}/><main className="container-shell py-10"><div><p className="text-sm font-bold uppercase tracking-widest text-blue-700">Integrações</p><h1 className="mt-1 text-3xl font-black">Canais oficiais</h1><p className="muted mt-2">Nada aparece como conectado antes da validação real do provider.</p></div>{status?<p className="mt-5 rounded-xl bg-emerald-50 p-4 text-sm font-semibold">Integração atualizada: {status}.</p>:null}{error?<p className="mt-5 rounded-xl bg-amber-50 p-4 text-sm">Não foi possível concluir ({error}). Revise credenciais, permissões e configurações.</p>:null}

  <section className="mt-7 grid gap-5 lg:grid-cols-2">
    <article className="card p-6"><div className="flex items-center justify-between gap-3"><div><h2 className="text-xl font-black">E-mail transacional</h2><p className="muted mt-1 text-sm">Provider: Resend.</p></div><Badge active={emailAllowed&&isTransactionalEmailConfigured()} label={emailAllowed?(isTransactionalEmailConfigured()?"Configurado":"Aguardando ambiente"):"Fora do plano"}/></div>{emailAllowed?<div className="mt-5 text-sm"><p>Envios manuais e e-mails de sistema usam a conta server-side da plataforma.</p><p className="muted mt-2">O status <strong>delivered</strong> só é gravado depois do Webhook assinado do Resend.</p><div className="mt-4 rounded-xl border border-black/10 p-4"><p className="font-bold">Webhook de entrega</p><p className="muted mt-1 break-all">{appUrl?`${appUrl}/api/webhooks/resend`:"Configure NEXT_PUBLIC_APP_URL para obter a URL final."}</p><p className="muted mt-2">Assinatura Svix: {isResendWebhookConfigured()?"configurada":"ainda não configurada"}.</p></div></div>:<p className="muted mt-5 text-sm">Disponível em plano com e-mail transacional. <Link href="/assinatura" className="font-bold underline">Ver plano</Link>.</p>}</article>

    <article className="card p-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-xl font-black">WhatsApp oficial</h2><p className="muted mt-1 text-sm">Meta WhatsApp Business Platform — Cloud API.</p></div><Badge active={whatsapp?.status==="active"} label={whatsappAllowed?(whatsapp?.status||"Não conectado"):"Fora do plano"}/></div>{whatsappAllowed?<>{phone?<p className="mt-4 text-sm"><strong>{verifiedName||organization.name}</strong> · {phone}{quality?` · qualidade ${quality}`:""}</p>:null}{whatsapp?.last_error?<p className="mt-3 rounded-lg bg-amber-50 p-3 text-xs">Último erro: {whatsapp.last_error}</p>:null}{canManage?<form action={saveWhatsAppConnectionAction} className="mt-5 grid gap-3"><label className="field"><span>Phone Number ID</span><input name="phone_number_id" required inputMode="numeric" defaultValue={phoneId}/></label><label className="field"><span>WhatsApp Business Account ID (WABA)</span><input name="waba_id" required inputMode="numeric" defaultValue={wabaId}/></label><label className="field"><span>Access Token</span><input name="access_token" type="password" autoComplete="new-password" placeholder={whatsapp?"Deixe vazio para manter o token atual":"Cole o token do System User"}/><small className="muted">O token é criptografado antes de ser persistido e nunca volta para o navegador.</small></label><button className="btn-primary justify-self-start" type="submit">Salvar credenciais</button></form>:<p className="muted mt-4 text-sm">Somente proprietário ou administrador pode configurar.</p>}{canManage&&whatsapp?<div className="mt-4 flex flex-wrap gap-2"><form action={testWhatsAppConnectionAction}><button className="btn-secondary" type="submit">Validar com a Meta</button></form><form action={disconnectWhatsAppAction}><button className="btn-danger" type="submit">Desconectar</button></form></div>:null}<div className="mt-5 rounded-xl border border-black/10 p-4 text-sm"><p className="font-bold">Webhook</p><p className="muted mt-1 break-all">{appUrl?`${appUrl}/api/webhooks/whatsapp`:"Configure NEXT_PUBLIC_APP_URL para obter a URL final."}</p><p className="muted mt-2">Verificação GET + HMAC POST: {isWhatsAppWebhookConfigured()?"configuradas":"ainda não configuradas"}.</p></div></>:<p className="muted mt-5 text-sm">Disponível em plano com WhatsApp oficial. <Link href="/assinatura" className="font-bold underline">Ver plano</Link>.</p>}</article>

    <article className="card p-6"><div className="flex items-center justify-between gap-3"><div><h2 className="text-xl font-black">Google Calendar</h2><p className="muted mt-1 text-sm">Sincronização da Agenda via OAuth 2.0.</p></div><Badge active={calendar?.status==="active"} label={calendarAllowed?(calendar?.status||"Não conectado"):"Fora do plano"}/></div>{calendarAllowed?<div className="mt-5 text-sm">{calendarEmail?<p>Conta conectada: <strong>{calendarEmail}</strong></p>:null}<p className="muted mt-2">Agendamentos são sincronizados por outbox; falha do Google não desfaz o agendamento local.</p>{canManage?<div className="mt-4 flex gap-2">{calendar?.status==="active"?<form action={disconnectGoogleCalendarAction}><button className="btn-danger" type="submit">Desconectar</button></form>:<Link className="btn-primary" href="/api/integrations/google-calendar/start">Conectar Google Calendar</Link>}</div>:null}{!isGoogleCalendarConfigured()?<p className="mt-3 rounded-lg bg-amber-50 p-3 text-xs">Configure GOOGLE_OAUTH_CLIENT_ID, GOOGLE_OAUTH_CLIENT_SECRET e a chave de criptografia no servidor.</p>:null}</div>:<p className="muted mt-5 text-sm">Disponível em plano compatível. <Link href="/assinatura" className="font-bold underline">Ver plano</Link>.</p>}</article>

    <article className="card p-6"><div className="flex items-center justify-between gap-3"><div><h2 className="text-xl font-black">Google Maps</h2><p className="muted mt-1 text-sm">Geocoding v4 executado somente no servidor.</p></div><Badge active={mapsAllowed&&Boolean(org?.geocoded_at)} label={mapsAllowed?(org?.geocoded_at?"Endereço validado":"Aguardando validação"):"Fora do plano"}/></div>{mapsAllowed?<div className="mt-5 text-sm"><p>{org?.geocoded_address||[org?.address,org?.city,org?.state].filter(Boolean).join(", ")||"Cadastre o endereço em Configurações."}</p><p className="muted mt-2">A chave da API nunca é enviada ao navegador. O site público recebe apenas endereço/coordenadas validadas.</p>{canManage?<form action={geocodeOrganizationAddressAction} className="mt-4"><button className="btn-secondary" type="submit" disabled={!org?.address||!isGoogleMapsConfigured()}>Validar endereço no Google</button></form>:null}{mapsHref?<a className="mt-3 inline-block font-bold underline" href={mapsHref} target="_blank" rel="noreferrer">Abrir localização no Google Maps</a>:null}{!isGoogleMapsConfigured()?<p className="mt-3 rounded-lg bg-amber-50 p-3 text-xs">Configure GOOGLE_MAPS_API_KEY com restrições adequadas no Google Cloud.</p>:null}</div>:<p className="muted mt-5 text-sm">Disponível em plano compatível.</p>}</article>
  </section>
  <section className="card mt-6 p-5"><h2 className="font-black">Regras operacionais</h2><p className="muted mt-2 text-sm">Mensagens livres no WhatsApp só são liberadas dentro da janela de atendimento; fora dela o sistema exige template aprovado. Google Calendar é sincronizado de forma assíncrona e Google Maps é consultado somente no backend.</p></section></main></>;
}
