import "server-only";

type VercelDomain={name?:string;verified?:boolean;verification?:Array<{type?:string;domain?:string;value?:string;reason?:string}>;configuredBy?:string};
function config(){const token=process.env.VERCEL_ACCESS_TOKEN;const project=process.env.VERCEL_PROJECT_ID||process.env.VERCEL_PROJECT_NAME;if(!token||!project)throw new Error("VERCEL_DOMAINS_NOT_CONFIGURED");return{token,project,team:process.env.VERCEL_TEAM_ID||""};}
function query(team:string){return team?`?teamId=${encodeURIComponent(team)}`:"";}
async function request(path:string,method:string,body?:unknown){const {token}=config();const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),10000);try{const response=await fetch(`https://api.vercel.com${path}`,{method,headers:{authorization:`Bearer ${token}`,...(body?{"content-type":"application/json"}:{})},body:body?JSON.stringify(body):undefined,signal:controller.signal,cache:"no-store"});const text=await response.text();let data:any={};try{data=text?JSON.parse(text):{};}catch{}if(!response.ok){const code=typeof data?.error?.code==="string"?data.error.code:`HTTP_${response.status}`;throw new Error(`VERCEL_DOMAIN_${code}`);}return data as VercelDomain;}finally{clearTimeout(timer);}}
export function vercelDomainsConfigured(){return Boolean(process.env.VERCEL_ACCESS_TOKEN&&(process.env.VERCEL_PROJECT_ID||process.env.VERCEL_PROJECT_NAME));}
export function normalizeCustomDomain(raw:string){let value=raw.trim().toLowerCase().replace(/^https?:\/\//,"").split("/")[0].replace(/\.$/,"");if(value.includes(":")||value.length<4||value.length>253||!/^(?=.{4,253}$)(?:[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\.)+[a-z]{2,63}$/.test(value))throw new Error("CUSTOM_DOMAIN_INVALID");const appHost=(()=>{try{return new URL(process.env.NEXT_PUBLIC_APP_URL||"http://localhost").hostname.toLowerCase();}catch{return"";}})();if(value===appHost||value.endsWith(".localhost")||value.endsWith(".vercel.app"))throw new Error("CUSTOM_DOMAIN_RESERVED");return value;}
export async function addVercelDomain(domain:string){const {project,team}=config();try{return await request(`/v10/projects/${encodeURIComponent(project)}/domains${query(team)}`,"POST",{name:domain});}catch(error){if(error instanceof Error&&/domain.*exist|DOMAIN_ALREADY|HTTP_409/i.test(error.message))return getVercelDomain(domain);throw error;}}
export async function getVercelDomain(domain:string){const {project,team}=config();return request(`/v9/projects/${encodeURIComponent(project)}/domains/${encodeURIComponent(domain)}${query(team)}`,"GET");}
export async function verifyVercelDomain(domain:string){const {project,team}=config();await request(`/v9/projects/${encodeURIComponent(project)}/domains/${encodeURIComponent(domain)}/verify${query(team)}`,"POST");return getVercelDomain(domain);}
export async function removeVercelDomain(domain:string){const {project,team}=config();await request(`/v9/projects/${encodeURIComponent(project)}/domains/${encodeURIComponent(domain)}${query(team)}`,"DELETE");}
export function safeVercelDomainData(data:VercelDomain){return{verified:data.verified===true,verification:Array.isArray(data.verification)?data.verification.slice(0,10).map(v=>({type:v.type||null,domain:v.domain||null,value:v.value||null,reason:v.reason||null})):[]};}
