"use client";
import { useActionState } from "react";
import { createApiKeyAction,createWebhookEndpointAction,type SecretState } from "@/features/developer/actions";
const initial:SecretState={ok:false};

function SecretResult({state,label}:{state:SecretState;label:string}){if(state.error)return <p className="rounded-xl bg-amber-50 p-3 text-sm">{state.error}</p>;if(!state.secret)return null;return <div className="rounded-xl border border-emerald-200 bg-emerald-50 p-4"><p className="font-bold">{label} — copie agora</p><p className="muted mt-1 text-xs">Por segurança, o valor completo não será mostrado novamente.</p><code className="mt-3 block overflow-x-auto rounded-lg bg-white p-3 text-xs select-all">{state.secret}</code></div>;}

export function ApiKeyForm(){const[state,action,pending]=useActionState(createApiKeyAction,initial);return <form action={action} className="card grid gap-4 p-5"><h2 className="text-lg font-black">Nova chave de API</h2><label className="field"><span>Nome</span><input name="name" required maxLength={100} placeholder="Integração ERP"/></label><fieldset className="grid gap-2"><legend className="text-sm font-bold">Escopos</legend>{[["leads:read","Ler leads"],["leads:write","Criar leads"],["customers:read","Ler clientes"],["quotes:read","Ler orçamentos"]].map(([scope,label])=><label className="text-sm" key={scope}><input type="checkbox" name="scope" value={scope}/> {label}</label>)}</fieldset><label className="field"><span>Expira em (opcional)</span><input name="expires_at" type="datetime-local"/></label><button className="btn-primary" disabled={pending} type="submit">{pending?"Criando...":"Criar chave"}</button><SecretResult state={state} label="Chave criada"/></form>;}

export function WebhookForm(){const[state,action,pending]=useActionState(createWebhookEndpointAction,initial);const events=[["lead_created","Lead criado"],["lead_stage_changed","Etapa do lead alterada"],["lead_converted_to_customer","Lead virou cliente"],["quote_created","Orçamento criado"],["quote_viewed","Orçamento visualizado"],["quote_response","Resposta ao orçamento"],["appointment_created","Agendamento criado"],["appointment_status_changed","Status do agendamento"],["site_published","Site publicado"],["subscription_status_changed","Assinatura alterada"]];return <form action={action} className="card grid gap-4 p-5"><h2 className="text-lg font-black">Novo Webhook</h2><label className="field"><span>Nome</span><input name="name" required maxLength={100} placeholder="n8n produção"/></label><label className="field"><span>Endpoint HTTPS</span><input name="url" type="url" required placeholder="https://automacao.exemplo.com/webhook"/></label><fieldset className="grid gap-2"><legend className="text-sm font-bold">Eventos</legend>{events.map(([event,label])=><label className="text-sm" key={event}><input type="checkbox" name="event_type" value={event}/> {label}</label>)}</fieldset><button className="btn-primary" disabled={pending} type="submit">{pending?"Validando...":"Criar Webhook"}</button><SecretResult state={state} label="Segredo de assinatura"/></form>;}
